[aws]
region = "us-west-2"

[microvm]
name = "test"

[microvm.image]
# iam-role = "arn:aws:iam::123456789012:role/clankervm-build"

[microvm.image.artifact]
source = "."
# s3-bucket = "my-artifact-bucket"

[microvm.run]
# iam-role = "arn:aws:iam::123456789012:role/clankervm-run"
