schema-version = 1

[image]
name = "test"
region = "us-west-2"

[push]
context = "."
# artifact-bucket = "my-artifact-bucket"
# build-role-arn = "arn:aws:iam::123456789012:role/clankervm-build"

[run]
# execution-role-arn = "arn:aws:iam::123456789012:role/clankervm-run"
