[workspace]
git_release_enable = false
git_tag_name = "{{ package }}-v{{ version }}"
pr_branch_prefix = "release-plz/"
pr_name = "chore: release"
dependencies_update = true

[[package]]
name = "clankervm"
release = true
publish = false

[[package]]
name = "clankervm-server"
release = true
publish = false
